import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";
import { D1SessionStorage } from "~/d1-session-storage";
import getShopifyInstance from "~/shopify.server";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: ({ context }) => {
    if (!context.cloudflare.env.SHOPIFY_APP_URL) {
      context.cloudflare.env.SHOPIFY_APP_URL = context.cloudflare.request.url;
    }
    const db = new D1SessionStorage(context.cloudflare.env.DB);
    const shopify = getShopifyInstance(context.cloudflare.env, db);
    return {
      ...context,
      cloudflare: {
        ...context.cloudflare,
        cf: context.cloudflare.request.cf,
      },
      db,
      shopify,
    }
  },
});
