# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
name = "shopify-app-remix-cf"
handle = "shopify-app-remix-cf"
application_url = "https://shopify-app-remix-cf.pages.dev"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shopify-app-remix-cf.pages.dev/api/auth/callback" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
