// Generated by Wrangler on Fri May 17 2024 13:17:20 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  SCOPES: string;
  SHOP_CUSTOM_DOMAIN: string;
	SHOPIFY_API_KEY: string;
	SHOPIFY_API_SECRET: string;
	SHOPIFY_APP_URL: string;
	DB: D1Database;
}
